## 학습목표
 1. numpy에서 자주 사용되는 함수들을 사용해보기

In [1]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

In [3]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.03536774 0.09030405 0.89253636 0.52662192 0.83621748]
 [0.82751987 0.85178686 0.76085051 0.1508756  0.27414398]
 [0.89207082 0.07591766 0.95143242 0.91083838 0.62158416]]


#### 연산 함수
 - add, substract, multiply, divide

In [4]:
np.add(x, y)

array([[ 0.03536774,  1.09030405,  2.89253636,  3.52662192,  4.83621748],
       [ 5.82751987,  6.85178686,  7.76085051,  8.1508756 ,  9.27414398],
       [10.89207082, 11.07591766, 12.95143242, 13.91083838, 14.62158416]])

In [5]:
x + y

array([[ 0.03536774,  1.09030405,  2.89253636,  3.52662192,  4.83621748],
       [ 5.82751987,  6.85178686,  7.76085051,  8.1508756 ,  9.27414398],
       [10.89207082, 11.07591766, 12.95143242, 13.91083838, 14.62158416]])

In [6]:
x - y

array([[-0.03536774,  0.90969595,  1.10746364,  2.47337808,  3.16378252],
       [ 4.17248013,  5.14821314,  6.23914949,  7.8491244 ,  8.72585602],
       [ 9.10792918, 10.92408234, 11.04856758, 12.08916162, 13.37841584]])

In [7]:
x * y

array([[ 0.        ,  0.09030405,  1.78507272,  1.57986575,  3.3448699 ],
       [ 4.13759933,  5.11072118,  5.32595357,  1.20700482,  2.46729578],
       [ 8.92070819,  0.8350943 , 11.41718901, 11.84089898,  8.70217827]])

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [8]:
print(y)

[[0.03536774 0.09030405 0.89253636 0.52662192 0.83621748]
 [0.82751987 0.85178686 0.76085051 0.1508756  0.27414398]
 [0.89207082 0.07591766 0.95143242 0.91083838 0.62158416]]


In [11]:
np.mean(y)

0.579871187250897

In [12]:
y.mean()

0.579871187250897

In [13]:
np.max(y)

0.9514324173668433

In [21]:
np.argmax(y, axis=0)

array([2, 1, 2, 2, 0])

In [23]:
np.var(y), np.mean(y), np.median(y)

(0.11658473529781793, 0.579871187250897, 0.760850510122215)

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [24]:
y

array([[0.03536774, 0.09030405, 0.89253636, 0.52662192, 0.83621748],
       [0.82751987, 0.85178686, 0.76085051, 0.1508756 , 0.27414398],
       [0.89207082, 0.07591766, 0.95143242, 0.91083838, 0.62158416]])

In [26]:
np.sum(y)

8.698067808763456

In [27]:
np.cumsum(y)

array([0.03536774, 0.12567179, 1.01820815, 1.54483007, 2.38104754,
       3.20856741, 4.06035428, 4.82120479, 4.97208039, 5.24622436,
       6.13829518, 6.21421285, 7.16564526, 8.07648365, 8.69806781])

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [28]:
z = np.random.randn(10)
print(z)

[ 1.75175948  0.38440257  0.33484706  0.90094334  0.47401147  0.24062243
  1.71713288 -1.20293015  1.20852675  0.21327153]


In [32]:
print(np.any(z > 0))
print(np.all(z != 0))

True
True


#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [33]:
z = np.random.randn(10)
print(z)

[ 0.1021761  -0.78738237  1.71042473  0.37523964 -1.15100739  0.1429945
 -0.12521986  1.3819355  -0.12144565  2.25638603]


In [36]:
print(np.where(z > 0, z, 0))

[0.1021761  0.         1.71042473 0.37523964 0.         0.1429945
 0.         1.3819355  0.         2.25638603]
