### 학습목표
 - random 서브모듈 함수를 통해 ndarray 생성하기

In [1]:
import numpy as np

#### random 서브모듈

#### rand 함수
 - 0, 1사이의 분포로 랜덤한 ndarray 생성

In [6]:
np.random.rand() 

0.9320302252501568

#### randn함수
 - n: normal distribution(정규분포)
 - 정규분포로 샘플링된 랜덤 ndarray 생성

In [9]:
np.random.randn(3, 3, 4)

array([[[-0.2905178 ,  0.22622657, -0.06062667,  1.08049575],
        [-0.7842807 , -0.4313553 , -1.39532597,  0.89913877],
        [-0.61984091, -0.80560101,  0.13171009, -0.75633847]],

       [[ 0.34264925, -0.2592606 ,  0.47060011,  1.62960316],
        [ 0.81657116, -0.62173801,  0.20120526, -0.07962213],
        [-2.3514638 , -0.61481958,  0.96996537,  0.42143724]],

       [[-1.70493291,  0.29550873,  0.4596525 , -0.64381725],
        [ 0.2605617 ,  1.27711937,  0.23955699,  0.09129953],
        [ 0.66150089,  0.20799213,  1.0633157 , -0.44502761]]])

#### randint 함수
 - 특정 정수 사이에서 랜덤하게 샘플링

In [22]:
np.random.randint(1, 100, size=(3, 5, 2))

array([[[68, 54],
        [16, 44],
        [64, 11],
        [18, 22],
        [37, 36]],

       [[68, 86],
        [ 2, 31],
        [70, 15],
        [28, 19],
        [31,  3]],

       [[96, 22],
        [55, 57],
        [59, 41],
        [48, 73],
        [55, 63]]])

#### seed 함수
 - 랜덤한 값을 동일하게 다시 생성하고자 할때 사용

In [29]:
np.random.seed(42)

In [42]:
np.random.randn(3, 4)

array([[ 0.25988279,  0.78182287, -1.23695071, -1.32045661],
       [ 0.52194157,  0.29698467,  0.25049285,  0.34644821],
       [-0.68002472,  0.2322537 ,  0.29307247, -0.71435142]])

In [43]:
np.random.randn(3, 4)

array([[ 1.86577451,  0.47383292, -1.1913035 ,  0.65655361],
       [-0.97468167,  0.7870846 ,  1.15859558, -0.82068232],
       [ 0.96337613,  0.41278093,  0.82206016,  1.89679298]])

#### choice
 - 주어진 1차원 ndarray로 부터 랜덤으로 샘플링
 - 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [49]:
x = np.arange(1, 10, 1)
np.random.choice(x, size=(2, 2), replace=False)

array([[5, 4],
       [9, 6]])

#### 확률분포에 따른 ndarray 생성
 - uniform
 - normal 등등

In [51]:
np.random.uniform(1.0, 3.0, size=(4, 5))

array([[2.29992786, 2.40393375, 2.59158534, 2.78001068, 1.67599031],
       [1.75116591, 1.18796388, 2.15656028, 1.07188455, 1.93119604],
       [2.08528927, 1.5730825 , 2.18166652, 1.0610005 , 1.07469638],
       [2.64520112, 1.72038128, 1.25412103, 2.04448652, 2.53998711]])

In [52]:
np.random.standard_normal(size=(3, 4))

array([[ 0.54957635, -1.27087181,  2.38903596,  1.84341376],
       [ 1.36343549,  0.82876598,  0.01514328,  0.44207402],
       [ 1.04801974, -0.62856975, -0.44449874, -1.66913236]])

In [53]:
np.random.randn(3, 4)

array([[-0.77181908,  1.66130173, -0.33424709, -0.31784691],
       [ 0.31776703, -1.61222731,  0.94538169,  1.26640686],
       [ 0.37729627,  1.65135099, -1.32683177,  1.8437158 ]])